### ISSUE TITLE
Desktop mockup

### ISSUE THREAD

**Issue by pLabarta** [Decred-Bulls/dcronchain#1]
A desktop mockup on Figma is the first we need so that Pavel can start coding the site. This issue will include an updated list of the progress towards the mockup and any new components added to the mockup as a result from UX/UI research.

**Milestones:**

- [ ] Base
- [ ] Home view
- [ ] Chart view

**Base:**

- [ ] Top navigation:
  - [x] Logo
  - [x] Search bar (not a priority)
  - [ ] Charts link
  - [ ] Menu:
    - [ ] List of first 5 charts
    - [ ] Some Decred.org link
    - [ ] DCR data link
    - [ ] Dark/Light Theme Switch
    - [ ] Github
    - [ ] Social media
- [x] Footer (same as menu)

**Home**

- [ ] Quick access carousel
- [x] Featured carousel
- [x] Section
  - [x] Section Title
  - [x] Chart card
    - [x] Title
    - [x] Chart preview
    - [x] Category/Tags
    - [x] Description
    - [x] Date

**Chart**

- [ ] Title
- [ ] Category
- [ ] Plotly chart container
- [ ] Tags
- [ ] Description
  - [ ] Brief description view with read more button
  - [ ] Long description view
- [ ] Detailed info about lines/indicators/chartcomponents
  - [ ] Color
  - [ ] Name
  - [ ] Formula
  - [ ] Description
  - [ ] Relevance
- [ ] Related articles
- [ ] Share buttons
